spring.application.name=foodBridgeSystem

spring.datasource.url=jdbc:mysql://localhost:3306/foodbridge_db
spring.datasource.username=root
spring.datasource.password=insiya21

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=trueate.format_sql=true

# Gmail SMTP
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=foodbridge06@gmail.com
spring.mail.password=qgeb hdwm feua fmwf

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true